name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build IP Check
      run: |
        IP_RESPONSE=$(curl -s http://ip-api.com/line/?fields=status)
        if [ "$IP_RESPONSE" == "success" ]; then
          echo "Workflow successfully created"
        else
          echo "Build failed"
          exit 1
        fi 